### PR TITLE
Updated React up to 17 version. Added Material UI, Jest. 

### PR DESCRIPTION
**Pull request by a4k**

### CODE REVIEW

**Review by Lyubimov-Ruslan2 — APPROVED** [review]
Approved!

**Comment by alterfo** [comment]
Hello there!

How are you approving conflicting changes that do not bring business value? 
Shame on you!

Cheers! Bye

**Comment by Lyubimov-Ruslan2** [comment]
Hello! Can you explain, which of these do not bring business value?

**Comment by a4k** [comment]
Hi, @alterfo.
Yes, it seems that there're no business value. But it's not, for further development at a rapid pace, it is required to make these changes.
Also, I suppose there are no problem to approve merge request with one conflict file. It will be resolved. The most important thing for us to make code review process regular.
The main idea of this MR is updating React and adding Material UI.  
Thank you for your concern! Together we make perfect application.

**Comment by alterfo** [comment]
Just curious - if I was right or not?

**Pull request merged**
